stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE: "vitmer/mlopsclassification-model"

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

build:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE:$CI_COMMIT_SHA .
    - docker push $DOCKER_IMAGE:$CI_COMMIT_SHA
  only:
    changes:
      - Dockerfile
      - values.yaml
  tags:
    - docker

deploy:
  stage: deploy
  script:
    - helm upgrade --install fastapi ./fastapi/helm-chart -f ./fastapi/values.yaml --set image.tag=$CI_COMMIT_SHA
  only:
    changes:
      - values.yaml
      - charts/**
  tags:
    - k8s