image: docker:latest

services:
  - docker:dind

stages:
  - build
  - deploy

default:
  before_script:
    - echo "Starting pipeline..."

build:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE
  only:
    - main  # Только для ветки main

deploy:
  stage: deploy
  script:
    - echo "Deploying application"
  only:
    - main