stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE: "vitmer/mlopsclassification-model"

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin || { echo "Docker login failed"; exit 1; }

build:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE:$CI_COMMIT_SHA .
    - docker push $DOCKER_IMAGE:$CI_COMMIT_SHA
  only:
    changes:
      - Dockerfile
      - values.yaml
  tags:
    - docker

deploy:
  stage: deploy
  script:
    - echo "Deploying with Helm"
    - helm upgrade --install fastapi charts/fastapi -f charts/fastapi/values.yaml --set image.tag=$CI_COMMIT_SHA || { echo "Helm upgrade failed"; exit 1; }
  only:
    changes:
      - charts/fastapi/values.yaml
      - charts/fastapi/**
  tags:
    - k8s


    