apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
data:
  DATABASE_URL: "postgresql://admin:adminpassword@postgres-postgresql:5432/appdb"
  REDIS_URL: "redis-master:6379"

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
data:
  REDIS_PASSWORD: {{ .Values.redis.password | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | b64enc | quote }}